#!/usr/bin/env bash
# Format (or check) every HAND-WRITTEN .phel file, skipping the generated
# data ones.
#
# `phel format` is quadratic in the number of elements inside a single
# collection literal (phel-lang#3218), and the baked asset files are one
# enormous literal each. Measured on this project:
#
#   src/io/render/enemy_sprites_data.phel   486 KB   94.7 s
#   src/io/render/wall_texture_data.phel     17 KB    2.1 s
#   src/io/render/weapon_sprites_data.phel   33 KB    1.0 s
#   src/io/sound_data.phel                  1.3 MB    0.15 s   (long strings, not elements)
#   ... every other file, all 94 of them              ~2.5 s
#
# That put `composer format-check` at 124 s of a 173 s pre-commit gate:
# 70% of the wait, in the step that only answers yes or no. None of these
# files is ever hand-edited - a bake tool writes them - so formatting
# them is pure cost. `phel format` has no --exclude and `format-dirs` is
# directory-based, so the list is assembled here.
#
# Usage: tools/format-sources.sh [--dry-run]
set -uo pipefail

cd "$(cd "$(dirname "$0")/.." && pwd)" || exit 2

# Generated: written by tools/bake-*.phel, never by hand. Keep in sync
# with the ";; GENERATED by" / "Baked from" headers those tools emit.
generated=(
  src/io/render/enemy_sprites_data.phel
  src/io/render/weapon_sprites_data.phel
  src/io/render/wall_texture_data.phel
  src/io/sound_data.phel
)

skip_re="$(printf '%s\n' "${generated[@]}" | paste -sd'|' -)"

files=()
while IFS= read -r f; do
  files+=("$f")
done < <(find src tests -name '*.phel' | grep -Ev "^(\./)?($skip_re)$" | sort)

if [ "${#files[@]}" -eq 0 ]; then
  echo "format-sources: no .phel files found under src/ tests/ - wrong directory?"
  exit 2
fi

# Fail loudly if a listed generated file has been renamed or removed, so
# the skip list can never silently stop matching (and quietly hand the
# 95-second file back to every commit).
for g in "${generated[@]}"; do
  [ -f "$g" ] || { echo "format-sources: generated file '$g' not found; update the list in $0"; exit 2; }
done

exec vendor/bin/phel format "$@" "${files[@]}"
