#!/usr/bin/env bash
# Format (or check) every HAND-WRITTEN .phel file, skipping the generated
# data ones.
#
# `phel format` is quadratic in the number of elements inside a single
# collection literal (phel-lang#3218), and the baked asset files are one
# enormous literal each. Measured on this project:
#
#   src/io/render/enemy_sprites_data.phel   486 KB   94.7 s
#   src/io/render/wall_texture_data.phel     17 KB    2.1 s
#   src/io/render/weapon_sprites_data.phel   33 KB    1.0 s
#   src/io/sound_data.phel                  1.3 MB    0.15 s   (long strings, not elements)
#   ... every other file, all 94 of them              ~2.5 s
#
# That put `composer format-check` at 124 s of a 173 s pre-commit gate:
# 70% of the wait, in the step that only answers yes or no. None of these
# files is ever hand-edited - a bake tool writes them - so formatting
# them is pure cost. `phel format` has no --exclude and `format-dirs` is
# directory-based, so the list is assembled here.
#
# Usage: tools/format-sources.sh [--dry-run]
set -uo pipefail

cd "$(cd "$(dirname "$0")/.." && pwd)" || exit 2

# Generated: written by tools/bake-*.phel, never by hand. Keep in sync
# with the ";; GENERATED by" / "Baked from" headers those tools emit.
generated=(
  src/io/render/enemy_sprites_data.phel
  src/io/render/weapon_sprites_data.phel
  src/io/render/wall_texture_data.phel
  src/io/sound_data.phel
)

skip_re="$(printf '%s\n' "${generated[@]}" | paste -sd'|' -)"

files=()
while IFS= read -r f; do
  files+=("$f")
done < <(find src tests -name '*.phel' | grep -Ev "^(\./)?($skip_re)$" | sort)

if [ "${#files[@]}" -eq 0 ]; then
  echo "format-sources: no .phel files found under src/ tests/ - wrong directory?"
  exit 2
fi

# Fail loudly if a listed generated file has been renamed or removed, so
# the skip list can never silently stop matching (and quietly hand the
# 95-second file back to every commit).
for g in "${generated[@]}"; do
  [ -f "$g" ] || { echo "format-sources: generated file '$g' not found; update the list in $0"; exit 2; }
done

# --------------------------------------------------------------------------
# Check mode only: skip files that already passed, unchanged, under this same
# formatter.
#
# `format-check` is a yes/no question asked on every commit about ~90 files,
# nearly all of which the commit did not touch: 5.3s of a 28s gate spent
# re-deciding that a file nobody edited is still formatted. The formatter has
# no incremental mode, so the memory lives here - a list of "this exact content
# passed" hashes, keyed by composer.lock so a formatter upgrade (which can
# change what "formatted" means) starts an empty one.
#
# It only ever SKIPS work that would have passed: an entry is written after a
# clean run, and any edit changes the file's hash and puts it back in the list.
# Write mode never consults it - re-running the formatter over a formatted file
# is idempotent and cheap, and a cache that could suppress a WRITE would be a
# way to leave a file unformatted.
# --------------------------------------------------------------------------

is_check=0
for a in "$@"; do
  [ "$a" = "--dry-run" ] && is_check=1
done

hash_of() { md5 -q "$1" 2>/dev/null || md5sum "$1" | cut -d' ' -f1; }

if [ "$is_check" -eq 0 ]; then
  exec vendor/bin/phel format "$@" "${files[@]}"
fi

key="$(md5 -q composer.lock 2>/dev/null || md5sum composer.lock | cut -d' ' -f1)"
cache=".phel/format-ok-${key:0:12}.txt"
mkdir -p .phel

# One cache per formatter version; the others are dead weight.
for old in .phel/format-ok-*.txt; do
  [ -f "$old" ] || continue
  [ "$old" = "$cache" ] && continue
  echo "format-sources: pruning stale cache $old"
  rm -f "$old"
done

stale=()
for f in "${files[@]}"; do
  h="$(hash_of "$f")"
  if [ -f "$cache" ] && grep -qxF "$h  $f" "$cache"; then
    continue
  fi
  stale+=("$f")
done

skipped=$(( ${#files[@]} - ${#stale[@]} ))

if [ "${#stale[@]}" -eq 0 ]; then
  echo "format-sources: ${#files[@]} files, all unchanged since they last passed."
  exit 0
fi

echo "format-sources: checking ${#stale[@]} of ${#files[@]} files ($skipped unchanged since they last passed)."
vendor/bin/phel format "$@" "${stale[@]}"
status=$?
[ "$status" -ne 0 ] && exit "$status"

# Record only what just passed, and only after it passed.
tmp="$(mktemp "${TMPDIR:-/tmp}/phel-doom-fmt.XXXXXX")"
[ -f "$cache" ] && cat "$cache" > "$tmp"
for f in "${stale[@]}"; do
  echo "$(hash_of "$f")  $f" >> "$tmp"
done
sort -u "$tmp" > "$cache"
rm -f "$tmp"
exit 0
